# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/urp/rendering.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19unity/urp/rendering.proto\x12\x16plume.sample.unity.urp*\x9f\x01\n\x10\x41ntialiasingMode\x12\x1a\n\x16\x41NTIALIASING_MODE_NONE\x10\x00\x12\x33\n/ANTIALIASING_MODE_FAST_APPROXIMATE_ANTIALIASING\x10\x01\x12:\n6ANTIALIASING_MODE_SUBPIXEL_MORPHOLOGICAL_ANTI_ALIASING\x10\x02*s\n\x13\x41ntialiasingQuality\x12\x1c\n\x18\x41NTIALIASING_QUALITY_LOW\x10\x00\x12\x1f\n\x1b\x41NTIALIASING_QUALITY_MEDIUM\x10\x01\x12\x1d\n\x19\x41NTIALIASING_QUALITY_HIGH\x10\x02\x42\x19\xaa\x02\x16PLUME.Sample.Unity.URPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.urp.rendering_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\026PLUME.Sample.Unity.URP'
  _globals['_ANTIALIASINGMODE']._serialized_start=54
  _globals['_ANTIALIASINGMODE']._serialized_end=213
  _globals['_ANTIALIASINGQUALITY']._serialized_start=215
  _globals['_ANTIALIASINGQUALITY']._serialized_end=330
# @@protoc_insertion_point(module_scope)
