# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/bounds.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import vector3_pb2 as common_dot_vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommon/bounds.proto\x12\x13plume.sample.common\x1a\x14\x63ommon/vector3.proto\"e\n\x06\x42ounds\x12,\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x1c.plume.sample.common.Vector3\x12-\n\x07\x65xtents\x18\x02 \x01(\x0b\x32\x1c.plume.sample.common.Vector3B\x16\xaa\x02\x13PLUME.Sample.Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.bounds_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023PLUME.Sample.Common'
  _globals['_BOUNDS']._serialized_start=66
  _globals['_BOUNDS']._serialized_end=167
# @@protoc_insertion_point(module_scope)
