# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/color.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommon/color.proto\x12\x13plume.sample.common\"3\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\x02\x12\t\n\x01g\x18\x02 \x01(\x02\x12\t\n\x01\x62\x18\x03 \x01(\x02\x12\t\n\x01\x61\x18\x04 \x01(\x02\"\xda\x03\n\rColorGradient\x12\x34\n\x0b\x63olor_space\x18\x01 \x01(\x0e\x32\x1f.plume.sample.common.ColorSpace\x12=\n\x04mode\x18\x02 \x01(\x0e\x32/.plume.sample.common.ColorGradient.GradientMode\x12?\n\ncolor_keys\x18\x03 \x03(\x0b\x32+.plume.sample.common.ColorGradient.ColorKey\x12?\n\nalpha_keys\x18\x04 \x03(\x0b\x32+.plume.sample.common.ColorGradient.AlphaKey\x1a\x43\n\x08\x43olorKey\x12)\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x1a.plume.sample.common.Color\x12\x0c\n\x04time\x18\x02 \x01(\x02\x1a\'\n\x08\x41lphaKey\x12\r\n\x05\x61lpha\x18\x01 \x01(\x02\x12\x0c\n\x04time\x18\x02 \x01(\x02\"d\n\x0cGradientMode\x12\x17\n\x13GRADIENT_MODE_BLEND\x10\x00\x12\x17\n\x13GRADIENT_MODE_FIXED\x10\x01\x12\"\n\x1eGRADIENT_MODE_PERCEPTUAL_BLEND\x10\x02*Z\n\nColorSpace\x12\x1d\n\x19\x43OLOR_SPACE_UNINITIALIZED\x10\x00\x12\x15\n\x11\x43OLOR_SPACE_GAMMA\x10\x01\x12\x16\n\x12\x43OLOR_SPACE_LINEAR\x10\x02\x42\x16\xaa\x02\x13PLUME.Sample.Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.color_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023PLUME.Sample.Common'
  _globals['_COLORSPACE']._serialized_start=573
  _globals['_COLORSPACE']._serialized_end=663
  _globals['_COLOR']._serialized_start=43
  _globals['_COLOR']._serialized_end=94
  _globals['_COLORGRADIENT']._serialized_start=97
  _globals['_COLORGRADIENT']._serialized_end=571
  _globals['_COLORGRADIENT_COLORKEY']._serialized_start=361
  _globals['_COLORGRADIENT_COLORKEY']._serialized_end=428
  _globals['_COLORGRADIENT_ALPHAKEY']._serialized_start=430
  _globals['_COLORGRADIENT_ALPHAKEY']._serialized_end=469
  _globals['_COLORGRADIENT_GRADIENTMODE']._serialized_start=471
  _globals['_COLORGRADIENT_GRADIENTMODE']._serialized_end=571
# @@protoc_insertion_point(module_scope)
