# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/spherical_harmonics_l1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import vector4_pb2 as common_dot_vector4__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#common/spherical_harmonics_l1.proto\x12\x13plume.sample.common\x1a\x14\x63ommon/vector4.proto\"\x9a\x01\n\x14SphericalHarmonicsL1\x12*\n\x04shAr\x18\x01 \x01(\x0b\x32\x1c.plume.sample.common.Vector4\x12*\n\x04shAg\x18\x02 \x01(\x0b\x32\x1c.plume.sample.common.Vector4\x12*\n\x04shAb\x18\x03 \x01(\x0b\x32\x1c.plume.sample.common.Vector4B\x16\xaa\x02\x13PLUME.Sample.Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.spherical_harmonics_l1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023PLUME.Sample.Common'
  _globals['_SPHERICALHARMONICSL1']._serialized_start=83
  _globals['_SPHERICALHARMONICSL1']._serialized_end=237
# @@protoc_insertion_point(module_scope)
