# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/spherical_harmonics_l2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#common/spherical_harmonics_l2.proto\x12\x13plume.sample.common\"\x90\x03\n\x14SphericalHarmonicsL2\x12\x0c\n\x04shr0\x18\x01 \x01(\x02\x12\x0c\n\x04shr1\x18\x02 \x01(\x02\x12\x0c\n\x04shr2\x18\x03 \x01(\x02\x12\x0c\n\x04shr3\x18\x04 \x01(\x02\x12\x0c\n\x04shr4\x18\x05 \x01(\x02\x12\x0c\n\x04shr5\x18\x06 \x01(\x02\x12\x0c\n\x04shr6\x18\x07 \x01(\x02\x12\x0c\n\x04shr7\x18\x08 \x01(\x02\x12\x0c\n\x04shr8\x18\t \x01(\x02\x12\x0c\n\x04shg0\x18\n \x01(\x02\x12\x0c\n\x04shg1\x18\x0b \x01(\x02\x12\x0c\n\x04shg2\x18\x0c \x01(\x02\x12\x0c\n\x04shg3\x18\r \x01(\x02\x12\x0c\n\x04shg4\x18\x0e \x01(\x02\x12\x0c\n\x04shg5\x18\x0f \x01(\x02\x12\x0c\n\x04shg6\x18\x10 \x01(\x02\x12\x0c\n\x04shg7\x18\x11 \x01(\x02\x12\x0c\n\x04shg8\x18\x12 \x01(\x02\x12\x0c\n\x04shb0\x18\x13 \x01(\x02\x12\x0c\n\x04shb1\x18\x14 \x01(\x02\x12\x0c\n\x04shb2\x18\x15 \x01(\x02\x12\x0c\n\x04shb3\x18\x16 \x01(\x02\x12\x0c\n\x04shb4\x18\x17 \x01(\x02\x12\x0c\n\x04shb5\x18\x18 \x01(\x02\x12\x0c\n\x04shb6\x18\x19 \x01(\x02\x12\x0c\n\x04shb7\x18\x1a \x01(\x02\x12\x0c\n\x04shb8\x18\x1b \x01(\x02\x42\x16\xaa\x02\x13PLUME.Sample.Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.spherical_harmonics_l2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023PLUME.Sample.Common'
  _globals['_SPHERICALHARMONICSL2']._serialized_start=61
  _globals['_SPHERICALHARMONICSL2']._serialized_end=461
# @@protoc_insertion_point(module_scope)
