# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/settings/quality_settings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%unity/settings/quality_settings.proto\x12\x1bplume.sample.unity.settings\x1a\x17unity/identifiers.proto\"\x8e\x01\n\x15QualitySettingsUpdate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12J\n\x18render_pipeline_asset_id\x18\x02 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x00\x88\x01\x01\x42\x1b\n\x19_render_pipeline_asset_idB\x1e\xaa\x02\x1bPLUME.Sample.Unity.Settingsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.settings.quality_settings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\033PLUME.Sample.Unity.Settings'
  _globals['_QUALITYSETTINGSUPDATE']._serialized_start=96
  _globals['_QUALITYSETTINGSUPDATE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
