# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/lsl/lsl_stream.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    "",
    "plume/sample/lsl/lsl_stream.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!plume/sample/lsl/lsl_stream.proto\x12\x10plume.sample.lsl"H\n\nStreamOpen\x12\x1b\n\tstream_id\x18\x01 \x01(\tR\x08streamId\x12\x1d\n\nxml_header\x18\x02 \x01(\tR\txmlHeader"*\n\x0bStreamClose\x12\x1b\n\tstream_id\x18\x01 \x01(\tR\x08streamId"\x8f\x07\n\x0cStreamSample\x12\x1b\n\tstream_id\x18\x01 \x01(\tR\x08streamId\x12Q\n\x0c\x66loat_values\x18\x02 \x01(\x0b\x32,.plume.sample.lsl.StreamSample.RepeatedFloatH\x00R\x0b\x66loatValues\x12T\n\rdouble_values\x18\x03 \x01(\x0b\x32-.plume.sample.lsl.StreamSample.RepeatedDoubleH\x00R\x0c\x64oubleValues\x12T\n\rstring_values\x18\x04 \x01(\x0b\x32-.plume.sample.lsl.StreamSample.RepeatedStringH\x00R\x0cstringValues\x12N\n\x0bint8_values\x18\x05 \x01(\x0b\x32+.plume.sample.lsl.StreamSample.RepeatedInt8H\x00R\nint8Values\x12Q\n\x0cint16_values\x18\x06 \x01(\x0b\x32,.plume.sample.lsl.StreamSample.RepeatedInt16H\x00R\x0bint16Values\x12Q\n\x0cint32_values\x18\x07 \x01(\x0b\x32,.plume.sample.lsl.StreamSample.RepeatedInt32H\x00R\x0bint32Values\x12Q\n\x0cint64_values\x18\x08 \x01(\x0b\x32,.plume.sample.lsl.StreamSample.RepeatedInt64H\x00R\x0bint64Values\x1a%\n\rRepeatedFloat\x12\x14\n\x05value\x18\x01 \x03(\x02R\x05value\x1a&\n\x0eRepeatedDouble\x12\x14\n\x05value\x18\x01 \x03(\x01R\x05value\x1a&\n\x0eRepeatedString\x12\x14\n\x05value\x18\x01 \x03(\tR\x05value\x1a$\n\x0cRepeatedInt8\x12\x14\n\x05value\x18\x01 \x03(\x05R\x05value\x1a%\n\rRepeatedInt16\x12\x14\n\x05value\x18\x01 \x03(\x05R\x05value\x1a%\n\rRepeatedInt32\x12\x14\n\x05value\x18\x01 \x03(\x05R\x05value\x1a%\n\rRepeatedInt64\x12\x14\n\x05value\x18\x01 \x03(\x03R\x05valueB\x08\n\x06valuesB\x13\xaa\x02\x10PLUME.Sample.LSLb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "plume.sample.lsl.lsl_stream_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\252\002\020PLUME.Sample.LSL"
    _globals["_STREAMOPEN"]._serialized_start = 55
    _globals["_STREAMOPEN"]._serialized_end = 127
    _globals["_STREAMCLOSE"]._serialized_start = 129
    _globals["_STREAMCLOSE"]._serialized_end = 171
    _globals["_STREAMSAMPLE"]._serialized_start = 174
    _globals["_STREAMSAMPLE"]._serialized_end = 1085
    _globals["_STREAMSAMPLE_REPEATEDFLOAT"]._serialized_start = 803
    _globals["_STREAMSAMPLE_REPEATEDFLOAT"]._serialized_end = 840
    _globals["_STREAMSAMPLE_REPEATEDDOUBLE"]._serialized_start = 842
    _globals["_STREAMSAMPLE_REPEATEDDOUBLE"]._serialized_end = 880
    _globals["_STREAMSAMPLE_REPEATEDSTRING"]._serialized_start = 882
    _globals["_STREAMSAMPLE_REPEATEDSTRING"]._serialized_end = 920
    _globals["_STREAMSAMPLE_REPEATEDINT8"]._serialized_start = 922
    _globals["_STREAMSAMPLE_REPEATEDINT8"]._serialized_end = 958
    _globals["_STREAMSAMPLE_REPEATEDINT16"]._serialized_start = 960
    _globals["_STREAMSAMPLE_REPEATEDINT16"]._serialized_end = 997
    _globals["_STREAMSAMPLE_REPEATEDINT32"]._serialized_start = 999
    _globals["_STREAMSAMPLE_REPEATEDINT32"]._serialized_end = 1036
    _globals["_STREAMSAMPLE_REPEATEDINT64"]._serialized_start = 1038
    _globals["_STREAMSAMPLE_REPEATEDINT64"]._serialized_end = 1075
# @@protoc_insertion_point(module_scope)
