# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/ui/content_size_fitter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"unity/ui/content_size_fitter.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\"N\n\x17\x43ontentSizeFitterCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"O\n\x18\x43ontentSizeFitterDestroy\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"\xe4\x01\n\x17\x43ontentSizeFitterUpdate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x38\n\x0ehorizontal_fit\x18\x02 \x01(\x0e\x32\x1b.plume.sample.unity.FitModeH\x00\x88\x01\x01\x12\x36\n\x0cvertical_fit\x18\x03 \x01(\x0e\x32\x1b.plume.sample.unity.FitModeH\x01\x88\x01\x01\x42\x11\n\x0f_horizontal_fitB\x0f\n\r_vertical_fit*T\n\x07\x46itMode\x12\x1a\n\x16\x46IT_MODE_UNCONSTRAINED\x10\x00\x12\x15\n\x11\x46IT_MODE_MIN_SIZE\x10\x01\x12\x16\n\x12\x46IT_MODE_PREF_SIZE\x10\x02\x42\x18\xaa\x02\x15PLUME.Sample.Unity.UIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.ui.content_size_fitter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\025PLUME.Sample.Unity.UI'
  _globals['_FITMODE']._serialized_start=475
  _globals['_FITMODE']._serialized_end=559
  _globals['_CONTENTSIZEFITTERCREATE']._serialized_start=83
  _globals['_CONTENTSIZEFITTERCREATE']._serialized_end=161
  _globals['_CONTENTSIZEFITTERDESTROY']._serialized_start=163
  _globals['_CONTENTSIZEFITTERDESTROY']._serialized_end=242
  _globals['_CONTENTSIZEFITTERUPDATE']._serialized_start=245
  _globals['_CONTENTSIZEFITTERUPDATE']._serialized_end=473
# @@protoc_insertion_point(module_scope)
