# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/ui/content_size_fitter.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    "",
    "plume/sample/unity/ui/content_size_fitter.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n/plume/sample/unity/ui/content_size_fitter.proto\x12\x15plume.sample.unity.ui\x1a$plume/sample/unity/identifiers.proto\"`\n\x17\x43ontentSizeFitterCreate\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\"a\n\x18\x43ontentSizeFitterDestroy\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\"\x98\x02\n\x17\x43ontentSizeFitterUpdate\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\x12J\n\x0ehorizontal_fit\x18\x02 \x01(\x0e\x32\x1e.plume.sample.unity.ui.FitModeH\x00R\rhorizontalFit\x88\x01\x01\x12\x46\n\x0cvertical_fit\x18\x03 \x01(\x0e\x32\x1e.plume.sample.unity.ui.FitModeH\x01R\x0bverticalFit\x88\x01\x01\x42\x11\n\x0f_horizontal_fitB\x0f\n\r_vertical_fit*T\n\x07\x46itMode\x12\x1a\n\x16\x46IT_MODE_UNCONSTRAINED\x10\x00\x12\x15\n\x11\x46IT_MODE_MIN_SIZE\x10\x01\x12\x16\n\x12\x46IT_MODE_PREF_SIZE\x10\x02\x42\x18\xaa\x02\x15PLUME.Sample.Unity.UIb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "plume.sample.unity.ui.content_size_fitter_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\252\002\025PLUME.Sample.Unity.UI"
    _globals["_FITMODE"]._serialized_start = 592
    _globals["_FITMODE"]._serialized_end = 676
    _globals["_CONTENTSIZEFITTERCREATE"]._serialized_start = 112
    _globals["_CONTENTSIZEFITTERCREATE"]._serialized_end = 208
    _globals["_CONTENTSIZEFITTERDESTROY"]._serialized_start = 210
    _globals["_CONTENTSIZEFITTERDESTROY"]._serialized_end = 307
    _globals["_CONTENTSIZEFITTERUPDATE"]._serialized_start = 310
    _globals["_CONTENTSIZEFITTERUPDATE"]._serialized_end = 590
# @@protoc_insertion_point(module_scope)
