# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/ui/graphic.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    "",
    "plume/sample/unity/ui/graphic.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n#plume/sample/unity/ui/graphic.proto\x12\x15plume.sample.unity.ui\x1a$plume/sample/unity/identifiers.proto\x1a!plume/sample/common/vector4.proto\x1a\x1fplume/sample/common/color.proto\"\x89\x03\n\rGraphicUpdate\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\x12\x35\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x1a.plume.sample.common.ColorH\x00R\x05\x63olor\x88\x01\x01\x12*\n\x0eraycast_target\x18\x03 \x01(\x08H\x01R\rraycastTarget\x88\x01\x01\x12J\n\x0fraycast_padding\x18\x04 \x01(\x0b\x32\x1c.plume.sample.common.Vector4H\x02R\x0eraycastPadding\x88\x01\x01\x12\x44\n\x08material\x18\x05 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x03R\x08material\x88\x01\x01\x42\x08\n\x06_colorB\x11\n\x0f_raycast_targetB\x12\n\x10_raycast_paddingB\x0b\n\t_materialB\x18\xaa\x02\x15PLUME.Sample.Unity.UIb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "plume.sample.unity.ui.graphic_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\252\002\025PLUME.Sample.Unity.UI"
    _globals["_GRAPHICUPDATE"]._serialized_start = 169
    _globals["_GRAPHICUPDATE"]._serialized_end = 562
# @@protoc_insertion_point(module_scope)
