# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/ui/image.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    "",
    "plume/sample/unity/ui/image.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n!plume/sample/unity/ui/image.proto\x12\x15plume.sample.unity.ui\x1a$plume/sample/unity/identifiers.proto\"T\n\x0bImageCreate\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\"U\n\x0cImageDestroy\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\"\xe5\x01\n\x0bImageUpdate\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\x12@\n\x06sprite\x18\x02 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x00R\x06sprite\x88\x01\x01\x12\x39\n\x04type\x18\x03 \x01(\x0e\x32 .plume.sample.unity.ui.ImageTypeH\x01R\x04type\x88\x01\x01\x42\t\n\x07_spriteB\x07\n\x05_type*f\n\tImageType\x12\x15\n\x11IMAGE_TYPE_SIMPLE\x10\x00\x12\x15\n\x11IMAGE_TYPE_SLICED\x10\x01\x12\x14\n\x10IMAGE_TYPE_TILED\x10\x02\x12\x15\n\x11IMAGE_TYPE_FILLED\x10\x03\x42\x18\xaa\x02\x15PLUME.Sample.Unity.UIb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "plume.sample.unity.ui.image_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\252\002\025PLUME.Sample.Unity.UI"
    _globals["_IMAGETYPE"]._serialized_start = 503
    _globals["_IMAGETYPE"]._serialized_end = 605
    _globals["_IMAGECREATE"]._serialized_start = 98
    _globals["_IMAGECREATE"]._serialized_end = 182
    _globals["_IMAGEDESTROY"]._serialized_start = 184
    _globals["_IMAGEDESTROY"]._serialized_end = 269
    _globals["_IMAGEUPDATE"]._serialized_start = 272
    _globals["_IMAGEUPDATE"]._serialized_end = 501
# @@protoc_insertion_point(module_scope)
