# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/common/animation_curve.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'plume/sample/common/animation_curve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)plume/sample/common/animation_curve.proto\x12\x13plume.sample.common\"[\n\x0e\x41nimationCurve\x12I\n\tkeyframes\x18\x01 \x03(\x0b\x32+.plume.sample.common.AnimationCurveKeyFrameR\tkeyframes\"\x86\x02\n\x16\x41nimationCurveKeyFrame\x12\x12\n\x04time\x18\x01 \x01(\x02R\x04time\x12\x14\n\x05value\x18\x02 \x01(\x02R\x05value\x12\x1d\n\nin_tangent\x18\x03 \x01(\x02R\tinTangent\x12\x1f\n\x0bout_tangent\x18\x04 \x01(\x02R\noutTangent\x12\x46\n\rweighted_mode\x18\x05 \x01(\x0e\x32!.plume.sample.common.WeightedModeR\x0cweightedMode\x12\x1b\n\tin_weight\x18\x06 \x01(\x02R\x08inWeight\x12\x1d\n\nout_weight\x18\x07 \x01(\x02R\toutWeight*k\n\x0cWeightedMode\x12\x16\n\x12WEIGHTED_MODE_NONE\x10\x00\x12\x14\n\x10WEIGHTED_MODE_IN\x10\x01\x12\x15\n\x11WEIGHTED_MODE_OUT\x10\x02\x12\x16\n\x12WEIGHTED_MODE_BOTH\x10\x03\x42\x16\xaa\x02\x13PLUME.Sample.Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plume.sample.common.animation_curve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023PLUME.Sample.Common'
  _globals['_WEIGHTEDMODE']._serialized_start=424
  _globals['_WEIGHTEDMODE']._serialized_end=531
  _globals['_ANIMATIONCURVE']._serialized_start=66
  _globals['_ANIMATIONCURVE']._serialized_end=157
  _globals['_ANIMATIONCURVEKEYFRAME']._serialized_start=160
  _globals['_ANIMATIONCURVEKEYFRAME']._serialized_end=422
# @@protoc_insertion_point(module_scope)
