# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/common/spherical_harmonics_l1.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'plume/sample/common/spherical_harmonics_l1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from plume.sample.common import vector4_pb2 as plume_dot_sample_dot_common_dot_vector4__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0plume/sample/common/spherical_harmonics_l1.proto\x12\x13plume.sample.common\x1a!plume/sample/common/vector4.proto\"\xaf\x01\n\x14SphericalHarmonicsL1\x12\x31\n\x05sh_ar\x18\x01 \x01(\x0b\x32\x1c.plume.sample.common.Vector4R\x04shAr\x12\x31\n\x05sh_ag\x18\x02 \x01(\x0b\x32\x1c.plume.sample.common.Vector4R\x04shAg\x12\x31\n\x05sh_ab\x18\x03 \x01(\x0b\x32\x1c.plume.sample.common.Vector4R\x04shAbB\x16\xaa\x02\x13PLUME.Sample.Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plume.sample.common.spherical_harmonics_l1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023PLUME.Sample.Common'
  _globals['_SPHERICALHARMONICSL1']._serialized_start=109
  _globals['_SPHERICALHARMONICSL1']._serialized_end=284
# @@protoc_insertion_point(module_scope)
