# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/settings/graphics_settings.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'plume/sample/unity/settings/graphics_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from plume.sample.unity import identifiers_pb2 as plume_dot_sample_dot_unity_dot_identifiers__pb2
from plume.sample.common import color_pb2 as plume_dot_sample_dot_common_dot_color__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3plume/sample/unity/settings/graphics_settings.proto\x12\x1bplume.sample.unity.settings\x1a$plume/sample/unity/identifiers.proto\x1a\x1fplume/sample/common/color.proto\"\xbc\x01\n\x10GraphicsSettings\x12\x66\n\x1d\x64\x65\x66\x61ult_render_pipeline_asset\x18\x01 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierR\x1a\x64\x65\x66\x61ultRenderPipelineAsset\x12@\n\x0b\x63olor_space\x18\x02 \x01(\x0e\x32\x1f.plume.sample.common.ColorSpaceR\ncolorSpaceB\x1e\xaa\x02\x1bPLUME.Sample.Unity.Settingsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plume.sample.unity.settings.graphics_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\033PLUME.Sample.Unity.Settings'
  _globals['_GRAPHICSSETTINGS']._serialized_start=156
  _globals['_GRAPHICSSETTINGS']._serialized_end=344
# @@protoc_insertion_point(module_scope)
