# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/xritk/input_action.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import vector2_pb2 as common_dot_vector2__pb2
from common import vector3_pb2 as common_dot_vector3__pb2
from common import quaternion_pb2 as common_dot_quaternion__pb2
from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eunity/xritk/input_action.proto\x12\x18plume.sample.unity.xritk\x1a\x14\x63ommon/vector2.proto\x1a\x14\x63ommon/vector3.proto\x1a\x17\x63ommon/quaternion.proto\x1a\x17unity/identifiers.proto\"\xc4\x03\n\x0bInputAction\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rbinding_paths\x18\x03 \x03(\t\x12\x37\n\x04type\x18\x04 \x01(\x0e\x32).plume.sample.unity.xritk.InputActionType\x12\x11\n\x07\x62oolean\x18\x05 \x01(\x08H\x00\x12\x11\n\x07integer\x18\x06 \x01(\x05H\x00\x12\x0f\n\x05\x66loat\x18\x07 \x01(\x02H\x00\x12\x10\n\x06\x64ouble\x18\x08 \x01(\x01H\x00\x12/\n\x07vector2\x18\t \x01(\x0b\x32\x1c.plume.sample.common.Vector2H\x00\x12/\n\x07vector3\x18\n \x01(\x0b\x32\x1c.plume.sample.common.Vector3H\x00\x12\x35\n\nquaternion\x18\x0b \x01(\x0b\x32\x1f.plume.sample.common.QuaternionH\x00\x12\x37\n\x06\x62utton\x18\x0c \x01(\x0b\x32%.plume.sample.unity.xritk.ButtonValueH\x00\x42\x07\n\x05value\"@\n\x0b\x42uttonValue\x12\x0f\n\x07\x62oolean\x18\x01 \x01(\x08\x12\r\n\x05\x66loat\x18\x02 \x01(\x02\x12\x11\n\tthreshold\x18\x03 \x01(\x02*9\n\x0fInputActionType\x12\t\n\x05VALUE\x10\x00\x12\n\n\x06\x42UTTON\x10\x01\x12\x0f\n\x0bPASSTHROUGH\x10\x02\x42\x1b\xaa\x02\x18PLUME.Sample.Unity.XRITKb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.xritk.input_action_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\030PLUME.Sample.Unity.XRITK'
  _globals['_INPUTACTIONTYPE']._serialized_start=675
  _globals['_INPUTACTIONTYPE']._serialized_end=732
  _globals['_INPUTACTION']._serialized_start=155
  _globals['_INPUTACTION']._serialized_end=607
  _globals['_BUTTONVALUE']._serialized_start=609
  _globals['_BUTTONVALUE']._serialized_end=673
# @@protoc_insertion_point(module_scope)
