# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/xritk/xritk_interaction.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'plume/sample/unity/xritk/xritk_interaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from plume.sample.unity import identifiers_pb2 as plume_dot_sample_dot_unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0plume/sample/unity/xritk/xritk_interaction.proto\x12\x18plume.sample.unity.xritk\x1a$plume/sample/unity/identifiers.proto\"\xec\x01\n\x10XRITKInteraction\x12K\n\x0cinteractable\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifierR\x0cinteractable\x12G\n\ninteractor\x18\x02 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifierR\ninteractor\x12\x42\n\x04type\x18\x03 \x01(\x0e\x32..plume.sample.unity.xritk.XRITKInteractionTypeR\x04type*\xb3\x02\n\x14XRITKInteractionType\x12&\n\"XRITK_INTERACTION_TYPE_UNSPECIFIED\x10\x00\x12&\n\"XRITK_INTERACTION_TYPE_HOVER_ENTER\x10\x01\x12%\n!XRITK_INTERACTION_TYPE_HOVER_EXIT\x10\x02\x12\'\n#XRITK_INTERACTION_TYPE_SELECT_ENTER\x10\x03\x12&\n\"XRITK_INTERACTION_TYPE_SELECT_EXIT\x10\x04\x12)\n%XRITK_INTERACTION_TYPE_ACTIVATE_ENTER\x10\x05\x12(\n$XRITK_INTERACTION_TYPE_ACTIVATE_EXIT\x10\x06\x42\x1b\xaa\x02\x18PLUME.Sample.Unity.XRITKb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plume.sample.unity.xritk.xritk_interaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\030PLUME.Sample.Unity.XRITK'
  _globals['_XRITKINTERACTIONTYPE']._serialized_start=356
  _globals['_XRITKINTERACTIONTYPE']._serialized_end=663
  _globals['_XRITKINTERACTION']._serialized_start=117
  _globals['_XRITKINTERACTION']._serialized_end=353
# @@protoc_insertion_point(module_scope)
