# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/scene.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11unity/scene.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\"<\n\tLoadScene\x12/\n\x02id\x18\x01 \x01(\x0b\x32#.plume.sample.unity.SceneIdentifier\">\n\x0bUnloadScene\x12/\n\x02id\x18\x01 \x01(\x0b\x32#.plume.sample.unity.SceneIdentifier\"D\n\x11\x43hangeActiveScene\x12/\n\x02id\x18\x01 \x01(\x0b\x32#.plume.sample.unity.SceneIdentifierB\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.scene_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_LOADSCENE']._serialized_start=66
  _globals['_LOADSCENE']._serialized_end=126
  _globals['_UNLOADSCENE']._serialized_start=128
  _globals['_UNLOADSCENE']._serialized_end=190
  _globals['_CHANGEACTIVESCENE']._serialized_start=192
  _globals['_CHANGEACTIVESCENE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
