# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packed_sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13packed_sample.proto\x12\x0cplume.sample\x1a\x19google/protobuf/any.proto\"[\n\x0cPackedSample\x12\x16\n\ttimestamp\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyB\x0c\n\n_timestampB\x0f\xaa\x02\x0cPLUME.Sampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packed_sample_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014PLUME.Sample'
  _globals['_PACKEDSAMPLE']._serialized_start=64
  _globals['_PACKEDSAMPLE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
