# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record_version.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14record_version.proto\x12\x0cplume.sample\"L\n\x0fRecorderVersion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05major\x18\x02 \x01(\t\x12\r\n\x05minor\x18\x03 \x01(\t\x12\r\n\x05patch\x18\x04 \x01(\tB\x0f\xaa\x02\x0cPLUME.Sampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record_version_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014PLUME.Sample'
  _globals['_RECORDERVERSION']._serialized_start=38
  _globals['_RECORDERVERSION']._serialized_end=114
# @@protoc_insertion_point(module_scope)
