# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import record_version_pb2 as record__version__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15record_metadata.proto\x12\x0cplume.sample\x1a\x14record_version.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n\x0eRecordMetadata\x12\x37\n\x10recorder_version\x18\x01 \x01(\x0b\x32\x1d.plume.sample.RecorderVersion\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nidentifier\x18\x03 \x01(\t\x12\x12\n\nsequential\x18\x04 \x01(\x08\x12\x16\n\x0e\x65xtra_metadata\x18\x05 \x01(\t\x12\x15\n\rsamples_count\x18\x06 \x01(\x06\x12\x10\n\x08\x64uration\x18\x07 \x01(\x06\x42\x0f\xaa\x02\x0cPLUME.Sampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record_metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014PLUME.Sample'
  _globals['_RECORDMETADATA']._serialized_start=95
  _globals['_RECORDMETADATA']._serialized_end=321
# @@protoc_insertion_point(module_scope)
