# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample_header.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sample_header.proto\x12\x0cplume.sample\")\n\x0cSampleHeader\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\x0b\n\x03seq\x18\x02 \x01(\rB\x0f\xaa\x02\x0cPLUME.Sampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_header_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014PLUME.Sample'
  _globals['_SAMPLEHEADER']._serialized_start=37
  _globals['_SAMPLEHEADER']._serialized_end=78
# @@protoc_insertion_point(module_scope)
