# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/settings/audio_settings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#unity/settings/audio_settings.proto\x12\x1bplume.sample.unity.settings\"\xab\x01\n\x13\x41udioSettingsUpdate\x12\x42\n\x0bspeakerMode\x18\x01 \x01(\x0e\x32(.plume.sample.unity.settings.SpeakerModeH\x00\x88\x01\x01\x12$\n\x17spatializer_plugin_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_speakerModeB\x1a\n\x18_spatializer_plugin_name*\xd0\x01\n\x0bSpeakerMode\x12\x15\n\x11SPEAKER_MODE_MONO\x10\x00\x12\x17\n\x13SPEAKER_MODE_STEREO\x10\x01\x12\x15\n\x11SPEAKER_MODE_QUAD\x10\x02\x12\x19\n\x15SPEAKER_MODE_SURROUND\x10\x03\x12!\n\x1dSPEAKER_MODE_SURROUND_5POINT1\x10\x04\x12!\n\x1dSPEAKER_MODE_SURROUND_7POINT1\x10\x05\x12\x19\n\x15SPEAKER_MODE_PROLOGIC\x10\x06\x42\x1e\xaa\x02\x1bPLUME.Sample.Unity.Settingsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.settings.audio_settings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\033PLUME.Sample.Unity.Settings'
  _globals['_SPEAKERMODE']._serialized_start=243
  _globals['_SPEAKERMODE']._serialized_end=451
  _globals['_AUDIOSETTINGSUPDATE']._serialized_start=69
  _globals['_AUDIOSETTINGSUPDATE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
