# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/urp/rendering.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'plume/sample/unity/urp/rendering.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&plume/sample/unity/urp/rendering.proto\x12\x16plume.sample.unity.urp*\x9f\x01\n\x10\x41ntialiasingMode\x12\x1a\n\x16\x41NTIALIASING_MODE_NONE\x10\x00\x12\x33\n/ANTIALIASING_MODE_FAST_APPROXIMATE_ANTIALIASING\x10\x01\x12:\n6ANTIALIASING_MODE_SUBPIXEL_MORPHOLOGICAL_ANTI_ALIASING\x10\x02*s\n\x13\x41ntialiasingQuality\x12\x1c\n\x18\x41NTIALIASING_QUALITY_LOW\x10\x00\x12\x1f\n\x1b\x41NTIALIASING_QUALITY_MEDIUM\x10\x01\x12\x1d\n\x19\x41NTIALIASING_QUALITY_HIGH\x10\x02\x42\x19\xaa\x02\x16PLUME.Sample.Unity.URPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plume.sample.unity.urp.rendering_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\026PLUME.Sample.Unity.URP'
  _globals['_ANTIALIASINGMODE']._serialized_start=67
  _globals['_ANTIALIASINGMODE']._serialized_end=226
  _globals['_ANTIALIASINGQUALITY']._serialized_start=228
  _globals['_ANTIALIASINGQUALITY']._serialized_end=343
# @@protoc_insertion_point(module_scope)
