# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/urp/volume.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'plume/sample/unity/urp/volume.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from plume.sample.unity import identifiers_pb2 as plume_dot_sample_dot_unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#plume/sample/unity/urp/volume.proto\x12\x16plume.sample.unity.urp\x1a$plume/sample/unity/identifiers.proto\"U\n\x0cVolumeCreate\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifierR\tcomponent\"V\n\rVolumeDestroy\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifierR\tcomponent\"\xa7\x04\n\x0cVolumeUpdate\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifierR\tcomponent\x12 \n\tis_global\x18\x02 \x01(\x08H\x00R\x08isGlobal\x88\x01\x01\x12Q\n\tcolliders\x18\x03 \x01(\x0b\x32..plume.sample.unity.urp.VolumeUpdate.CollidersH\x01R\tcolliders\x88\x01\x01\x12*\n\x0e\x62lend_distance\x18\x04 \x01(\x02H\x02R\rblendDistance\x88\x01\x01\x12\x1b\n\x06weight\x18\x05 \x01(\x02H\x03R\x06weight\x88\x01\x01\x12\x1f\n\x08priority\x18\x06 \x01(\x02H\x04R\x08priority\x88\x01\x01\x12O\n\x0eshared_profile\x18\x07 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x05R\rsharedProfile\x88\x01\x01\x1a\x46\n\tColliders\x12\x39\n\x03ids\x18\x01 \x03(\x0b\x32\'.plume.sample.unity.ComponentIdentifierR\x03idsB\x0c\n\n_is_globalB\x0c\n\n_collidersB\x11\n\x0f_blend_distanceB\t\n\x07_weightB\x0b\n\t_priorityB\x11\n\x0f_shared_profile\"v\n\x13VolumeUpdateEnabled\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifierR\tcomponent\x12\x18\n\x07\x65nabled\x18\x02 \x01(\x08R\x07\x65nabledB\x19\xaa\x02\x16PLUME.Sample.Unity.URPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plume.sample.unity.urp.volume_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\026PLUME.Sample.Unity.URP'
  _globals['_VOLUMECREATE']._serialized_start=101
  _globals['_VOLUMECREATE']._serialized_end=186
  _globals['_VOLUMEDESTROY']._serialized_start=188
  _globals['_VOLUMEDESTROY']._serialized_end=274
  _globals['_VOLUMEUPDATE']._serialized_start=277
  _globals['_VOLUMEUPDATE']._serialized_end=828
  _globals['_VOLUMEUPDATE_COLLIDERS']._serialized_start=668
  _globals['_VOLUMEUPDATE_COLLIDERS']._serialized_end=738
  _globals['_VOLUMEUPDATEENABLED']._serialized_start=830
  _globals['_VOLUMEUPDATEENABLED']._serialized_end=948
# @@protoc_insertion_point(module_scope)
