# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crecord.proto\x12\x0cplume.sample\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n\x0fRecorderVersion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05major\x18\x02 \x01(\t\x12\r\n\x05minor\x18\x03 \x01(\t\x12\r\n\x05patch\x18\x04 \x01(\t\"\x9f\x01\n\x0eRecordMetadata\x12\x37\n\x10recorder_version\x18\x01 \x01(\x0b\x32\x1d.plume.sample.RecorderVersion\x12.\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x16\n\x0e\x65xtra_metadata\x18\x04 \x01(\t\"K\n\rRecordMetrics\x12\x15\n\ris_sequential\x18\x01 \x01(\x08\x12\x10\n\x08\x64uration\x18\x02 \x01(\x04\x12\x11\n\tn_samples\x18\x03 \x01(\x04\x42\x0f\xaa\x02\x0cPLUME.Sampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014PLUME.Sample'
  _globals['_RECORDERVERSION']._serialized_start=63
  _globals['_RECORDERVERSION']._serialized_end=139
  _globals['_RECORDMETADATA']._serialized_start=142
  _globals['_RECORDMETADATA']._serialized_end=301
  _globals['_RECORDMETRICS']._serialized_start=303
  _globals['_RECORDMETRICS']._serialized_end=378
# @@protoc_insertion_point(module_scope)
