# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lsl/stream_open.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lsl import stream_info_pb2 as lsl_dot_stream__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15lsl/stream_open.proto\x12\x10plume.sample.lsl\x1a\x15lsl/stream_info.proto\"S\n\nStreamOpen\x12\x31\n\x0bstream_info\x18\x01 \x01(\x0b\x32\x1c.plume.sample.lsl.StreamInfo\x12\x12\n\nxml_header\x18\x02 \x01(\tB\x13\xaa\x02\x10PLUME.Sample.LSLb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lsl.stream_open_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020PLUME.Sample.LSL'
  _globals['_STREAMOPEN']._serialized_start=66
  _globals['_STREAMOPEN']._serialized_end=149
# @@protoc_insertion_point(module_scope)
