# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lsl/stream_close.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lsl import stream_info_pb2 as lsl_dot_stream__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16lsl/stream_close.proto\x12\x10plume.sample.lsl\x1a\x15lsl/stream_info.proto\"@\n\x0bStreamClose\x12\x31\n\x0bstream_info\x18\x01 \x01(\x0b\x32\x1c.plume.sample.lsl.StreamInfoB\x13\xaa\x02\x10PLUME.Sample.LSLb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lsl.stream_close_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\020PLUME.Sample.LSL'
  _globals['_STREAMCLOSE']._serialized_start=67
  _globals['_STREAMCLOSE']._serialized_end=131
# @@protoc_insertion_point(module_scope)
