# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lsl/stream_info.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15lsl/stream_info.proto\x12\x10plume.sample.lsl\"\x8b\x01\n\nStreamInfo\x12\x1b\n\x13plume_raw_timestamp\x18\x01 \x01(\x04\x12\x18\n\x10lsl_plume_offset\x18\x02 \x01(\x03\x12\x15\n\rlsl_timestamp\x18\x03 \x01(\x01\x12\x18\n\x10lsl_clock_offset\x18\x04 \x01(\x01\x12\x15\n\rlsl_stream_id\x18\x05 \x01(\tB\x13\xaa\x02\x10PLUME.Sample.LSLb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lsl.stream_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020PLUME.Sample.LSL'
  _globals['_STREAMINFO']._serialized_start=44
  _globals['_STREAMINFO']._serialized_end=183
# @@protoc_insertion_point(module_scope)
