# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/record.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'plume/sample/record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19plume/sample/record.proto\x12\x0cplume.sample\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\x0fRecorderVersion\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n\x05major\x18\x02 \x01(\tR\x05major\x12\x14\n\x05minor\x18\x03 \x01(\tR\x05minor\x12\x14\n\x05patch\x18\x04 \x01(\tR\x05patch\"\xd0\x01\n\x0eRecordMetadata\x12H\n\x10recorder_version\x18\x01 \x01(\x0b\x32\x1d.plume.sample.RecorderVersionR\x0frecorderVersion\x12\x39\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartTime\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12%\n\x0e\x65xtra_metadata\x18\x04 \x01(\tR\rextraMetadata\"m\n\rRecordMetrics\x12#\n\ris_sequential\x18\x01 \x01(\x08R\x0cisSequential\x12\x1a\n\x08\x64uration\x18\x02 \x01(\x04R\x08\x64uration\x12\x1b\n\tn_samples\x18\x03 \x01(\x04R\x08nSamplesB\x0f\xaa\x02\x0cPLUME.Sampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plume.sample.record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014PLUME.Sample'
  _globals['_RECORDERVERSION']._serialized_start=76
  _globals['_RECORDERVERSION']._serialized_end=179
  _globals['_RECORDMETADATA']._serialized_start=182
  _globals['_RECORDMETADATA']._serialized_end=390
  _globals['_RECORDMETRICS']._serialized_start=392
  _globals['_RECORDMETRICS']._serialized_end=501
# @@protoc_insertion_point(module_scope)
