# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/game_object.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17unity/game_object.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\"Q\n\x10GameObjectCreate\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\"R\n\x11GameObjectDestroy\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\"c\n\x14GameObjectUpdateName\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12\x0c\n\x04name\x18\x02 \x01(\t\"k\n\x1aGameObjectUpdateActiveSelf\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\"a\n\x13GameObjectUpdateTag\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12\x0b\n\x03tag\x18\x02 \x01(\t\"e\n\x15GameObjectUpdateLayer\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12\r\n\x05layer\x18\x02 \x01(\x05\"h\n\x15GameObjectUpdateScene\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12\x10\n\x08scene_id\x18\x02 \x01(\x05\x42\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.game_object_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_GAMEOBJECTCREATE']._serialized_start=72
  _globals['_GAMEOBJECTCREATE']._serialized_end=153
  _globals['_GAMEOBJECTDESTROY']._serialized_start=155
  _globals['_GAMEOBJECTDESTROY']._serialized_end=237
  _globals['_GAMEOBJECTUPDATENAME']._serialized_start=239
  _globals['_GAMEOBJECTUPDATENAME']._serialized_end=338
  _globals['_GAMEOBJECTUPDATEACTIVESELF']._serialized_start=340
  _globals['_GAMEOBJECTUPDATEACTIVESELF']._serialized_end=447
  _globals['_GAMEOBJECTUPDATETAG']._serialized_start=449
  _globals['_GAMEOBJECTUPDATETAG']._serialized_end=546
  _globals['_GAMEOBJECTUPDATELAYER']._serialized_start=548
  _globals['_GAMEOBJECTUPDATELAYER']._serialized_end=649
  _globals['_GAMEOBJECTUPDATESCENE']._serialized_start=651
  _globals['_GAMEOBJECTUPDATESCENE']._serialized_end=755
# @@protoc_insertion_point(module_scope)
