# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/identifiers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17unity/identifiers.proto\x12\x12plume.sample.unity\"D\n\x14GameObjectIdentifier\x12\x16\n\x0egame_object_id\x18\x01 \x01(\t\x12\x14\n\x0ctransform_id\x18\x02 \x01(\t\"h\n\x13\x43omponentIdentifier\x12\x14\n\x0c\x63omponent_id\x18\x01 \x01(\t\x12;\n\tparent_id\x18\x02 \x01(\x0b\x32(.plume.sample.unity.GameObjectIdentifier\"+\n\x0f\x41ssetIdentifier\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"\x96\x01\n\x0fSceneIdentifier\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rruntime_index\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x13\n\x0b\x62uild_index\x18\x05 \x01(\x05\x12/\n\x04mode\x18\x06 \x01(\x0e\x32!.plume.sample.unity.LoadSceneMode*I\n\rLoadSceneMode\x12\x1a\n\x16LOAD_SCENE_MODE_SINGLE\x10\x00\x12\x1c\n\x18LOAD_SCENE_MODE_ADDITIVE\x10\x01\x42\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.identifiers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_LOADSCENEMODE']._serialized_start=421
  _globals['_LOADSCENEMODE']._serialized_end=494
  _globals['_GAMEOBJECTIDENTIFIER']._serialized_start=47
  _globals['_GAMEOBJECTIDENTIFIER']._serialized_end=115
  _globals['_COMPONENTIDENTIFIER']._serialized_start=117
  _globals['_COMPONENTIDENTIFIER']._serialized_end=221
  _globals['_ASSETIDENTIFIER']._serialized_start=223
  _globals['_ASSETIDENTIFIER']._serialized_end=266
  _globals['_SCENEIDENTIFIER']._serialized_start=269
  _globals['_SCENEIDENTIFIER']._serialized_end=419
# @@protoc_insertion_point(module_scope)
