# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/identifiers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17unity/identifiers.proto\x12\x12plume.sample.unity\"M\n\x1dTransformGameObjectIdentifier\x12\x14\n\x0ctransform_id\x18\x01 \x01(\t\x12\x16\n\x0egame_object_id\x18\x02 \x01(\t\"g\n\x13\x43omponentIdentifier\x12\n\n\x02id\x18\x01 \x01(\t\x12\x44\n\tparent_id\x18\x02 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\"(\n\x1a\x43omponentDestroyIdentifier\x12\n\n\x02id\x18\x01 \x01(\t\"9\n\x0f\x41ssetIdentifier\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04hash\x18\x03 \x01(\x05\x42\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.identifiers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_TRANSFORMGAMEOBJECTIDENTIFIER']._serialized_start=47
  _globals['_TRANSFORMGAMEOBJECTIDENTIFIER']._serialized_end=124
  _globals['_COMPONENTIDENTIFIER']._serialized_start=126
  _globals['_COMPONENTIDENTIFIER']._serialized_end=229
  _globals['_COMPONENTDESTROYIDENTIFIER']._serialized_start=231
  _globals['_COMPONENTDESTROYIDENTIFIER']._serialized_end=271
  _globals['_ASSETIDENTIFIER']._serialized_start=273
  _globals['_ASSETIDENTIFIER']._serialized_end=330
# @@protoc_insertion_point(module_scope)
