# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/mesh_filter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17unity/mesh_filter.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\"G\n\x10MeshFilterCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"H\n\x11MeshFilterDestroy\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"\x8e\x01\n\x10MeshFilterUpdate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x39\n\x07mesh_id\x18\x02 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x00\x88\x01\x01\x42\n\n\x08_mesh_idB\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.mesh_filter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_MESHFILTERCREATE']._serialized_start=72
  _globals['_MESHFILTERCREATE']._serialized_end=143
  _globals['_MESHFILTERDESTROY']._serialized_start=145
  _globals['_MESHFILTERDESTROY']._serialized_end=217
  _globals['_MESHFILTERUPDATE']._serialized_start=220
  _globals['_MESHFILTERUPDATE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
