# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/mesh_renderer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2
from common import vector4_pb2 as common_dot_vector4__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19unity/mesh_renderer.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\x1a\x14\x63ommon/vector4.proto\"I\n\x12MeshRendererCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"a\n\x19MeshRendererUpdateEnabled\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\"\x8e\x01\n\x1bMeshRendererUpdateMaterials\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12:\n\rmaterials_ids\x18\x02 \x03(\x0b\x32#.plume.sample.unity.AssetIdentifier\"\x8d\x02\n\x1aMeshRendererUpdateLightmap\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x16\n\x0elightmap_index\x18\x02 \x01(\x05\x12;\n\x15lightmap_scale_offset\x18\x03 \x01(\x0b\x32\x1c.plume.sample.common.Vector4\x12\x1f\n\x17realtime_lightmap_index\x18\x04 \x01(\x05\x12\x44\n\x1erealtime_lightmap_scale_offset\x18\x05 \x01(\x0b\x32\x1c.plume.sample.common.Vector4B\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.mesh_renderer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_MESHRENDERERCREATE']._serialized_start=96
  _globals['_MESHRENDERERCREATE']._serialized_end=169
  _globals['_MESHRENDERERUPDATEENABLED']._serialized_start=171
  _globals['_MESHRENDERERUPDATEENABLED']._serialized_end=268
  _globals['_MESHRENDERERUPDATEMATERIALS']._serialized_start=271
  _globals['_MESHRENDERERUPDATEMATERIALS']._serialized_end=413
  _globals['_MESHRENDERERUPDATELIGHTMAP']._serialized_start=416
  _globals['_MESHRENDERERUPDATELIGHTMAP']._serialized_end=685
# @@protoc_insertion_point(module_scope)
