# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/rect_transform.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import vector2_pb2 as common_dot_vector2__pb2
from common import vector3_pb2 as common_dot_vector3__pb2
from common import quaternion_pb2 as common_dot_quaternion__pb2
from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aunity/rect_transform.proto\x12\x12plume.sample.unity\x1a\x14\x63ommon/vector2.proto\x1a\x14\x63ommon/vector3.proto\x1a\x17\x63ommon/quaternion.proto\x1a\x17unity/identifiers.proto\"J\n\x13RectTransformCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"K\n\x14RectTransformDestroy\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"\xb8\x05\n\x13RectTransformUpdate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12?\n\tparent_id\x18\x02 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifierH\x00\x88\x01\x01\x12\x18\n\x0bsibling_idx\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x39\n\x0elocal_position\x18\x04 \x01(\x0b\x32\x1c.plume.sample.common.Vector3H\x02\x88\x01\x01\x12<\n\x0elocal_rotation\x18\x05 \x01(\x0b\x32\x1f.plume.sample.common.QuaternionH\x03\x88\x01\x01\x12\x36\n\x0blocal_scale\x18\x06 \x01(\x0b\x32\x1c.plume.sample.common.Vector3H\x04\x88\x01\x01\x12\x35\n\nanchor_min\x18\x07 \x01(\x0b\x32\x1c.plume.sample.common.Vector2H\x05\x88\x01\x01\x12\x35\n\nanchor_max\x18\x08 \x01(\x0b\x32\x1c.plume.sample.common.Vector2H\x06\x88\x01\x01\x12\x35\n\nsize_delta\x18\t \x01(\x0b\x32\x1c.plume.sample.common.Vector2H\x07\x88\x01\x01\x12\x30\n\x05pivot\x18\n \x01(\x0b\x32\x1c.plume.sample.common.Vector2H\x08\x88\x01\x01\x42\x0c\n\n_parent_idB\x0e\n\x0c_sibling_idxB\x11\n\x0f_local_positionB\x11\n\x0f_local_rotationB\x0e\n\x0c_local_scaleB\r\n\x0b_anchor_minB\r\n\x0b_anchor_maxB\r\n\x0b_size_deltaB\x08\n\x06_pivotB\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.rect_transform_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_RECTTRANSFORMCREATE']._serialized_start=144
  _globals['_RECTTRANSFORMCREATE']._serialized_end=218
  _globals['_RECTTRANSFORMDESTROY']._serialized_start=220
  _globals['_RECTTRANSFORMDESTROY']._serialized_end=295
  _globals['_RECTTRANSFORMUPDATE']._serialized_start=298
  _globals['_RECTTRANSFORMUPDATE']._serialized_end=994
# @@protoc_insertion_point(module_scope)
