# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/skinned_mesh_renderer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!unity/skinned_mesh_renderer.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\"P\n\x19SkinnedMeshRendererCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"Q\n\x1aSkinnedMeshRendererDestroy\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"\xa5\x05\n\x19SkinnedMeshRendererUpdate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x39\n\x07mesh_id\x18\x02 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x00\x88\x01\x01\x12\x42\n\x0croot_bone_id\x18\x03 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifierH\x01\x88\x01\x01\x12G\n\x05\x62ones\x18\x04 \x01(\x0b\x32\x33.plume.sample.unity.SkinnedMeshRendererUpdate.BonesH\x02\x88\x01\x01\x12\x61\n\x13\x62lend_shape_weights\x18\x05 \x01(\x0b\x32?.plume.sample.unity.SkinnedMeshRendererUpdate.BlendShapeWeightsH\x03\x88\x01\x01\x1a=\n\x05\x42ones\x12\x34\n\x03ids\x18\x01 \x03(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x1a\xa9\x01\n\x11\x42lendShapeWeights\x12\x61\n\x07weights\x18\x01 \x03(\x0b\x32P.plume.sample.unity.SkinnedMeshRendererUpdate.BlendShapeWeights.BlendShapeWeight\x1a\x31\n\x10\x42lendShapeWeight\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0e\n\x06weight\x18\x02 \x01(\x02\x42\n\n\x08_mesh_idB\x0f\n\r_root_bone_idB\x08\n\x06_bonesB\x16\n\x14_blend_shape_weightsB\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.skinned_mesh_renderer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_SKINNEDMESHRENDERERCREATE']._serialized_start=82
  _globals['_SKINNEDMESHRENDERERCREATE']._serialized_end=162
  _globals['_SKINNEDMESHRENDERERDESTROY']._serialized_start=164
  _globals['_SKINNEDMESHRENDERERDESTROY']._serialized_end=245
  _globals['_SKINNEDMESHRENDERERUPDATE']._serialized_start=248
  _globals['_SKINNEDMESHRENDERERUPDATE']._serialized_end=925
  _globals['_SKINNEDMESHRENDERERUPDATE_BONES']._serialized_start=629
  _globals['_SKINNEDMESHRENDERERUPDATE_BONES']._serialized_end=690
  _globals['_SKINNEDMESHRENDERERUPDATE_BLENDSHAPEWEIGHTS']._serialized_start=693
  _globals['_SKINNEDMESHRENDERERUPDATE_BLENDSHAPEWEIGHTS']._serialized_end=862
  _globals['_SKINNEDMESHRENDERERUPDATE_BLENDSHAPEWEIGHTS_BLENDSHAPEWEIGHT']._serialized_start=813
  _globals['_SKINNEDMESHRENDERERUPDATE_BLENDSHAPEWEIGHTS_BLENDSHAPEWEIGHT']._serialized_end=862
# @@protoc_insertion_point(module_scope)
