# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/terrain_collider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cunity/terrain_collider.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\"L\n\x15TerrainColliderCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"M\n\x16TerrainColliderDestroy\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"\x94\x02\n\x15TerrainColliderUpdate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x14\n\x07\x65nabled\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12\x41\n\x0fterrain_data_id\x18\x03 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x01\x88\x01\x01\x12=\n\x0bmaterial_id\x18\x04 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x02\x88\x01\x01\x42\n\n\x08_enabledB\x12\n\x10_terrain_data_idB\x0e\n\x0c_material_idB\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.terrain_collider_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_TERRAINCOLLIDERCREATE']._serialized_start=77
  _globals['_TERRAINCOLLIDERCREATE']._serialized_end=153
  _globals['_TERRAINCOLLIDERDESTROY']._serialized_start=155
  _globals['_TERRAINCOLLIDERDESTROY']._serialized_end=232
  _globals['_TERRAINCOLLIDERUPDATE']._serialized_start=235
  _globals['_TERRAINCOLLIDERUPDATE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
