# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/transform.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import vector3_pb2 as common_dot_vector3__pb2
from common import quaternion_pb2 as common_dot_quaternion__pb2
from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15unity/transform.proto\x12\x12plume.sample.unity\x1a\x14\x63ommon/vector3.proto\x1a\x17\x63ommon/quaternion.proto\x1a\x17unity/identifiers.proto\"P\n\x0fTransformCreate\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\"Q\n\x10TransformDestroy\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\"s\n\x1bTransformUpdateSiblingIndex\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12\x15\n\rsibling_index\x18\x02 \x01(\x05\"\xaf\x01\n\x15TransformUpdateParent\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12I\n\tparent_id\x18\x02 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifierH\x00\x88\x01\x01\x42\x0c\n\n_parent_id\"\xc4\x01\n\x17TransformUpdatePosition\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12\x34\n\x0elocal_position\x18\x02 \x01(\x0b\x32\x1c.plume.sample.common.Vector3\x12\x34\n\x0eworld_position\x18\x03 \x01(\x0b\x32\x1c.plume.sample.common.Vector3\"\xca\x01\n\x17TransformUpdateRotation\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12\x37\n\x0elocal_rotation\x18\x02 \x01(\x0b\x32\x1f.plume.sample.common.Quaternion\x12\x37\n\x0eworld_rotation\x18\x03 \x01(\x0b\x32\x1f.plume.sample.common.Quaternion\"\xbb\x01\n\x14TransformUpdateScale\x12=\n\x02id\x18\x01 \x01(\x0b\x32\x31.plume.sample.unity.TransformGameObjectIdentifier\x12\x31\n\x0blocal_scale\x18\x02 \x01(\x0b\x32\x1c.plume.sample.common.Vector3\x12\x31\n\x0bworld_scale\x18\x03 \x01(\x0b\x32\x1c.plume.sample.common.Vector3B\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.transform_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_TRANSFORMCREATE']._serialized_start=117
  _globals['_TRANSFORMCREATE']._serialized_end=197
  _globals['_TRANSFORMDESTROY']._serialized_start=199
  _globals['_TRANSFORMDESTROY']._serialized_end=280
  _globals['_TRANSFORMUPDATESIBLINGINDEX']._serialized_start=282
  _globals['_TRANSFORMUPDATESIBLINGINDEX']._serialized_end=397
  _globals['_TRANSFORMUPDATEPARENT']._serialized_start=400
  _globals['_TRANSFORMUPDATEPARENT']._serialized_end=575
  _globals['_TRANSFORMUPDATEPOSITION']._serialized_start=578
  _globals['_TRANSFORMUPDATEPOSITION']._serialized_end=774
  _globals['_TRANSFORMUPDATEROTATION']._serialized_start=777
  _globals['_TRANSFORMUPDATEROTATION']._serialized_end=979
  _globals['_TRANSFORMUPDATESCALE']._serialized_start=982
  _globals['_TRANSFORMUPDATESCALE']._serialized_end=1169
# @@protoc_insertion_point(module_scope)
