# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/game_object.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    "",
    "plume/sample/unity/game_object.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$plume/sample/unity/game_object.proto\x12\x12plume.sample.unity\x1a$plume/sample/unity/identifiers.proto"L\n\x10GameObjectCreate\x12\x38\n\x02id\x18\x01 \x01(\x0b\x32(.plume.sample.unity.GameObjectIdentifierR\x02id"M\n\x11GameObjectDestroy\x12\x38\n\x02id\x18\x01 \x01(\x0b\x32(.plume.sample.unity.GameObjectIdentifierR\x02id"\xa4\x02\n\x10GameObjectUpdate\x12\x38\n\x02id\x18\x01 \x01(\x0b\x32(.plume.sample.unity.GameObjectIdentifierR\x02id\x12\x17\n\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n\x06\x61\x63tive\x18\x03 \x01(\x08H\x01R\x06\x61\x63tive\x88\x01\x01\x12\x15\n\x03tag\x18\x04 \x01(\tH\x02R\x03tag\x88\x01\x01\x12\x19\n\x05layer\x18\x05 \x01(\x05H\x03R\x05layer\x88\x01\x01\x12>\n\x05scene\x18\x06 \x01(\x0b\x32#.plume.sample.unity.SceneIdentifierH\x04R\x05scene\x88\x01\x01\x42\x07\n\x05_nameB\t\n\x07_activeB\x06\n\x04_tagB\x08\n\x06_layerB\x08\n\x06_sceneB\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "plume.sample.unity.game_object_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\252\002\022PLUME.Sample.Unity"
    _globals["_GAMEOBJECTCREATE"]._serialized_start = 98
    _globals["_GAMEOBJECTCREATE"]._serialized_end = 174
    _globals["_GAMEOBJECTDESTROY"]._serialized_start = 176
    _globals["_GAMEOBJECTDESTROY"]._serialized_end = 253
    _globals["_GAMEOBJECTUPDATE"]._serialized_start = 256
    _globals["_GAMEOBJECTUPDATE"]._serialized_end = 548
# @@protoc_insertion_point(module_scope)
