# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/identifiers.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'plume/sample/unity/identifiers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$plume/sample/unity/identifiers.proto\x12\x12plume.sample.unity\"\x8c\x01\n\x14GameObjectIdentifier\x12\x12\n\x04guid\x18\x01 \x01(\tR\x04guid\x12%\n\x0etransform_guid\x18\x02 \x01(\tR\rtransformGuid\x12\x39\n\x05scene\x18\x03 \x01(\x0b\x32#.plume.sample.unity.SceneIdentifierR\x05scene\"t\n\x13\x43omponentIdentifier\x12\x12\n\x04guid\x18\x01 \x01(\tR\x04guid\x12I\n\x0bgame_object\x18\x02 \x01(\x0b\x32(.plume.sample.unity.GameObjectIdentifierR\ngameObject\"Q\n\x0f\x41ssetIdentifier\x12\x12\n\x04guid\x18\x01 \x01(\tR\x04guid\x12*\n\x11\x61sset_bundle_path\x18\x02 \x01(\tR\x0f\x61ssetBundlePath\"e\n\x0fSceneIdentifier\x12\x12\n\x04guid\x18\x01 \x01(\tR\x04guid\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12*\n\x11\x61sset_bundle_path\x18\x03 \x01(\tR\x0f\x61ssetBundlePathB\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plume.sample.unity.identifiers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_GAMEOBJECTIDENTIFIER']._serialized_start=61
  _globals['_GAMEOBJECTIDENTIFIER']._serialized_end=201
  _globals['_COMPONENTIDENTIFIER']._serialized_start=203
  _globals['_COMPONENTIDENTIFIER']._serialized_end=319
  _globals['_ASSETIDENTIFIER']._serialized_start=321
  _globals['_ASSETIDENTIFIER']._serialized_end=402
  _globals['_SCENEIDENTIFIER']._serialized_start=404
  _globals['_SCENEIDENTIFIER']._serialized_end=505
# @@protoc_insertion_point(module_scope)
