# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/lightmap.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'plume/sample/unity/lightmap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from plume.sample.unity import identifiers_pb2 as plume_dot_sample_dot_unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!plume/sample/unity/lightmap.proto\x12\x12plume.sample.unity\x1a$plume/sample/unity/identifiers.proto\"\xa4\x01\n\x0fLightmapsUpdate\x12H\n\x0elightmaps_mode\x18\x01 \x01(\x0e\x32!.plume.sample.unity.LightmapsModeR\rlightmapsMode\x12G\n\x0elightmaps_data\x18\x02 \x03(\x0b\x32 .plume.sample.unity.LightmapDataR\rlightmapsData\"\x8a\x03\n\x0cLightmapData\x12^\n\x16lightmap_color_texture\x18\x01 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x00R\x14lightmapColorTexture\x88\x01\x01\x12Z\n\x14lightmap_dir_texture\x18\x02 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x01R\x12lightmapDirTexture\x88\x01\x01\x12i\n\x1clightmap_shadow_mask_texture\x18\x03 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x02R\x19lightmapShadowMaskTexture\x88\x01\x01\x42\x19\n\x17_lightmap_color_textureB\x17\n\x15_lightmap_dir_textureB\x1f\n\x1d_lightmap_shadow_mask_texture*\\\n\rLightmapsMode\x12\"\n\x1eLIGHTMAPS_MODE_NON_DIRECTIONAL\x10\x00\x12\'\n#LIGHTMAPS_MODE_COMBINED_DIRECTIONAL\x10\x01\x42\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plume.sample.unity.lightmap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\022PLUME.Sample.Unity'
  _globals['_LIGHTMAPSMODE']._serialized_start=659
  _globals['_LIGHTMAPSMODE']._serialized_end=751
  _globals['_LIGHTMAPSUPDATE']._serialized_start=96
  _globals['_LIGHTMAPSUPDATE']._serialized_end=260
  _globals['_LIGHTMAPDATA']._serialized_start=263
  _globals['_LIGHTMAPDATA']._serialized_end=657
# @@protoc_insertion_point(module_scope)
