# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/scene.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    "",
    "plume/sample/unity/scene.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1eplume/sample/unity/scene.proto\x12\x12plume.sample.unity\x1a$plume/sample/unity/identifiers.proto"}\n\tLoadScene\x12\x39\n\x05scene\x18\x01 \x01(\x0b\x32#.plume.sample.unity.SceneIdentifierR\x05scene\x12\x35\n\x04mode\x18\x02 \x01(\x0e\x32!.plume.sample.unity.LoadSceneModeR\x04mode"H\n\x0bUnloadScene\x12\x39\n\x05scene\x18\x01 \x01(\x0b\x32#.plume.sample.unity.SceneIdentifierR\x05scene"N\n\x11\x43hangeActiveScene\x12\x39\n\x05scene\x18\x01 \x01(\x0b\x32#.plume.sample.unity.SceneIdentifierR\x05scene*I\n\rLoadSceneMode\x12\x1a\n\x16LOAD_SCENE_MODE_SINGLE\x10\x00\x12\x1c\n\x18LOAD_SCENE_MODE_ADDITIVE\x10\x01\x42\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "plume.sample.unity.scene_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\252\002\022PLUME.Sample.Unity"
    _globals["_LOADSCENEMODE"]._serialized_start = 373
    _globals["_LOADSCENEMODE"]._serialized_end = 446
    _globals["_LOADSCENE"]._serialized_start = 92
    _globals["_LOADSCENE"]._serialized_end = 217
    _globals["_UNLOADSCENE"]._serialized_start = 219
    _globals["_UNLOADSCENE"]._serialized_end = 291
    _globals["_CHANGEACTIVESCENE"]._serialized_start = 293
    _globals["_CHANGEACTIVESCENE"]._serialized_end = 371
# @@protoc_insertion_point(module_scope)
