# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plume/sample/unity/transform.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    "",
    "plume/sample/unity/transform.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\"plume/sample/unity/transform.proto\x12\x12plume.sample.unity\x1a!plume/sample/common/vector3.proto\x1a$plume/sample/common/quaternion.proto\x1a$plume/sample/unity/identifiers.proto\"X\n\x0fTransformCreate\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\"Y\n\x10TransformDestroy\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\"\x8d\x04\n\x0fTransformUpdate\x12\x45\n\tcomponent\x18\x01 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierR\tcomponent\x12W\n\x10parent_transform\x18\x02 \x01(\x0b\x32'.plume.sample.unity.ComponentIdentifierH\x00R\x0fparentTransform\x88\x01\x01\x12$\n\x0bsibling_idx\x18\x03 \x01(\x05H\x01R\nsiblingIdx\x88\x01\x01\x12H\n\x0elocal_position\x18\x04 \x01(\x0b\x32\x1c.plume.sample.common.Vector3H\x02R\rlocalPosition\x88\x01\x01\x12K\n\x0elocal_rotation\x18\x05 \x01(\x0b\x32\x1f.plume.sample.common.QuaternionH\x03R\rlocalRotation\x88\x01\x01\x12\x42\n\x0blocal_scale\x18\x06 \x01(\x0b\x32\x1c.plume.sample.common.Vector3H\x04R\nlocalScale\x88\x01\x01\x42\x13\n\x11_parent_transformB\x0e\n\x0c_sibling_idxB\x11\n\x0f_local_positionB\x11\n\x0f_local_rotationB\x0e\n\x0c_local_scaleB\x15\xaa\x02\x12PLUME.Sample.Unityb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "plume.sample.unity.transform_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\252\002\022PLUME.Sample.Unity"
    _globals["_TRANSFORMCREATE"]._serialized_start = 169
    _globals["_TRANSFORMCREATE"]._serialized_end = 257
    _globals["_TRANSFORMDESTROY"]._serialized_start = 259
    _globals["_TRANSFORMDESTROY"]._serialized_end = 348
    _globals["_TRANSFORMUPDATE"]._serialized_start = 351
    _globals["_TRANSFORMUPDATE"]._serialized_end = 876
# @@protoc_insertion_point(module_scope)
