# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/ui/canvas_scaler.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cunity/ui/canvas_scaler.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\"I\n\x12\x43\x61nvasScalerCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"J\n\x13\x43\x61nvasScalerDestroy\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"\xd1\x01\n\x12\x43\x61nvasScalerUpdate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12$\n\x17\x64ynamic_pixels_per_unit\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12&\n\x19reference_pixels_per_unit\x18\x03 \x01(\x02H\x01\x88\x01\x01\x42\x1a\n\x18_dynamic_pixels_per_unitB\x1c\n\x1a_reference_pixels_per_unitB\x18\xaa\x02\x15PLUME.Sample.Unity.UIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.ui.canvas_scaler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\025PLUME.Sample.Unity.UI'
  _globals['_CANVASSCALERCREATE']._serialized_start=77
  _globals['_CANVASSCALERCREATE']._serialized_end=150
  _globals['_CANVASSCALERDESTROY']._serialized_start=152
  _globals['_CANVASSCALERDESTROY']._serialized_end=226
  _globals['_CANVASSCALERUPDATE']._serialized_start=229
  _globals['_CANVASSCALERUPDATE']._serialized_end=438
# @@protoc_insertion_point(module_scope)
