# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/ui/canvas_scaler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cunity/ui/canvas_scaler.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\"I\n\x12\x43\x61nvasScalerCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"\x9a\x01\n\x1f\x43\x61nvasScalerUpdatePixelsPerUnit\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x1f\n\x17\x64ynamic_pixels_per_unit\x18\x02 \x01(\x02\x12!\n\x19reference_pixels_per_unit\x18\x03 \x01(\x02\x42\x18\xaa\x02\x15PLUME.Sample.Unity.UIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.ui.canvas_scaler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\025PLUME.Sample.Unity.UI'
  _globals['_CANVASSCALERCREATE']._serialized_start=77
  _globals['_CANVASSCALERCREATE']._serialized_end=150
  _globals['_CANVASSCALERUPDATEPIXELSPERUNIT']._serialized_start=153
  _globals['_CANVASSCALERUPDATEPIXELSPERUNIT']._serialized_end=307
# @@protoc_insertion_point(module_scope)
