# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/ui/graphic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2
from common import vector4_pb2 as common_dot_vector4__pb2
from common import color_pb2 as common_dot_color__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16unity/ui/graphic.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\x1a\x14\x63ommon/vector4.proto\x1a\x12\x63ommon/color.proto\"\xcd\x02\n\rGraphicUpdate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12.\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x1a.plume.sample.common.ColorH\x00\x88\x01\x01\x12\x1b\n\x0eraycast_target\x18\x03 \x01(\x08H\x01\x88\x01\x01\x12:\n\x0fraycast_padding\x18\x04 \x01(\x0b\x32\x1c.plume.sample.common.Vector4H\x02\x88\x01\x01\x12=\n\x0bmaterial_id\x18\x05 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x03\x88\x01\x01\x42\x08\n\x06_colorB\x11\n\x0f_raycast_targetB\x12\n\x10_raycast_paddingB\x0e\n\x0c_material_idB\x18\xaa\x02\x15PLUME.Sample.Unity.UIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.ui.graphic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\025PLUME.Sample.Unity.UI'
  _globals['_GRAPHICUPDATE']._serialized_start=114
  _globals['_GRAPHICUPDATE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
