# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/ui/text.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2
from common import color_pb2 as common_dot_color__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13unity/ui/text.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\x1a\x12\x63ommon/color.proto\"A\n\nTextCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"T\n\x0fTextUpdateValue\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x0c\n\x04text\x18\x02 \x01(\t\"\xb3\x01\n\x0eTextUpdateFont\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x39\n\x07\x66ont_id\x18\x02 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x00\x88\x01\x01\x12\x12\n\nfont_style\x18\x03 \x01(\x05\x12\x11\n\tfont_size\x18\x04 \x01(\x05\x42\n\n\x08_font_id\"q\n\x0fTextUpdateColor\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12)\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x1a.plume.sample.common.Color\"\xbc\x02\n\x10TextUpdateExtras\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x14\n\x0cline_spacing\x18\x02 \x01(\x02\x12\x19\n\x11support_rich_text\x18\x03 \x01(\x08\x12\x11\n\talignment\x18\x04 \x01(\x05\x12\x19\n\x11\x61lign_by_geometry\x18\x05 \x01(\x08\x12\x1b\n\x13horizontal_overflow\x18\x06 \x01(\x05\x12\x19\n\x11vertical_overflow\x18\x07 \x01(\x05\x12 \n\x18resize_text_for_best_fit\x18\x08 \x01(\x08\x12\x1c\n\x14resize_text_min_size\x18\t \x01(\x05\x12\x1c\n\x14resize_text_max_size\x18\n \x01(\x05\x42\x18\xaa\x02\x15PLUME.Sample.Unity.UIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.ui.text_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\025PLUME.Sample.Unity.UI'
  _globals['_TEXTCREATE']._serialized_start=88
  _globals['_TEXTCREATE']._serialized_end=153
  _globals['_TEXTUPDATEVALUE']._serialized_start=155
  _globals['_TEXTUPDATEVALUE']._serialized_end=239
  _globals['_TEXTUPDATEFONT']._serialized_start=242
  _globals['_TEXTUPDATEFONT']._serialized_end=421
  _globals['_TEXTUPDATECOLOR']._serialized_start=423
  _globals['_TEXTUPDATECOLOR']._serialized_end=536
  _globals['_TEXTUPDATEEXTRAS']._serialized_start=539
  _globals['_TEXTUPDATEEXTRAS']._serialized_end=855
# @@protoc_insertion_point(module_scope)
