# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unity/ui/tmp_text.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from unity import identifiers_pb2 as unity_dot_identifiers__pb2
from common import vector4_pb2 as common_dot_vector4__pb2
from common import color_pb2 as common_dot_color__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17unity/ui/tmp_text.proto\x12\x12plume.sample.unity\x1a\x17unity/identifiers.proto\x1a\x14\x63ommon/vector4.proto\x1a\x12\x63ommon/color.proto\"D\n\rTMPTextCreate\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\"W\n\x12TMPTextUpdateValue\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x0c\n\x04text\x18\x02 \x01(\t\"\xf7\x01\n\x11TMPTextUpdateFont\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x39\n\x07\x66ont_id\x18\x02 \x01(\x0b\x32#.plume.sample.unity.AssetIdentifierH\x00\x88\x01\x01\x12\x12\n\nfont_style\x18\x03 \x01(\x05\x12\x11\n\tfont_size\x18\x04 \x01(\x02\x12\x11\n\tauto_size\x18\x05 \x01(\x08\x12\x15\n\rfont_size_min\x18\x06 \x01(\x02\x12\x15\n\rfont_size_max\x18\x07 \x01(\x02\x42\n\n\x08_font_id\"t\n\x12TMPTextUpdateColor\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12)\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x1a.plume.sample.common.Color\"\xcf\x02\n\x13TMPTextUpdateExtras\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.plume.sample.unity.ComponentIdentifier\x12\x19\n\x11\x63haracter_spacing\x18\x02 \x01(\x02\x12\x14\n\x0cword_spacing\x18\x03 \x01(\x02\x12\x14\n\x0cline_spacing\x18\x04 \x01(\x02\x12\x19\n\x11paragraph_spacing\x18\x05 \x01(\x02\x12\x18\n\x10wrapping_enabled\x18\x06 \x01(\x08\x12\x11\n\talignment\x18\x07 \x01(\x05\x12\x10\n\x08overflow\x18\x08 \x01(\x05\x12\x1a\n\x12horizontal_mapping\x18\t \x01(\x05\x12\x18\n\x10vertical_mapping\x18\n \x01(\x05\x12,\n\x06margin\x18\x0b \x01(\x0b\x32\x1c.plume.sample.common.Vector4B\x18\xaa\x02\x15PLUME.Sample.Unity.UIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unity.ui.tmp_text_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\025PLUME.Sample.Unity.UI'
  _globals['_TMPTEXTCREATE']._serialized_start=114
  _globals['_TMPTEXTCREATE']._serialized_end=182
  _globals['_TMPTEXTUPDATEVALUE']._serialized_start=184
  _globals['_TMPTEXTUPDATEVALUE']._serialized_end=271
  _globals['_TMPTEXTUPDATEFONT']._serialized_start=274
  _globals['_TMPTEXTUPDATEFONT']._serialized_end=521
  _globals['_TMPTEXTUPDATECOLOR']._serialized_start=523
  _globals['_TMPTEXTUPDATECOLOR']._serialized_end=639
  _globals['_TMPTEXTUPDATEEXTRAS']._serialized_start=642
  _globals['_TMPTEXTUPDATEEXTRAS']._serialized_end=977
# @@protoc_insertion_point(module_scope)
